name: Shelly HA Manager
version: "1.0.0"
slug: shelly_ha_manager
description: Manage your Shelly devices directly from Home Assistant
url: "https://github.com/filmgarage/ha-addon-shelly-manager"
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_port: 8099
host_network: true
ports:
  8099/tcp: 8099
homeassistant_api: true
hassio_api: true
hassio_role: admin
panel_icon: mdi:lightbulb-group
panel_title: Shelly Manager
image: ghcr.io/filmgarage/shelly-ha-manager-{arch}
options:
  admin_password: ""
schema:
  admin_password: password
